# https;//docs.gitlab.com/ce/ci/yaml/
stages:
  - check27
  - check
  - lint27
  - lint

variables:
  PIP_CACHE_DIR: pip-cache

cache:
  untracked: true
  paths:
  - pip-cache

# -- stages

check27:
  stage: check27
  image: python:2.7.13
  before_script:
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
    - pip install -r requirements.txt
    - pip install flake8
  script:
    - flake8 main.py
  except:
    - tags

check:
  stage: check
  image: python:3.5.4
  before_script:
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
    - pip install -r requirements.txt
    - pip install flake8
  script:
    - flake8 main.py
  except:
    - tags

lint27:
  stage: lint27
  image: python:2.7.13
  before_script:
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
    - pip install -r requirements.txt
    - pip install pylint
  script:
    - pylint main.py
  except:
    - tags

lint:
  stage: lint
  image: python:3.5.4
  before_script:
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
    - pip install -r requirements.txt
    - pip install pylint
  script:
    - pylint main.py
  except:
    - tags
