# https;//docs.gitlab.com/ce/ci/yaml/
stages:
  - check27
  - check
  - lint27
  - lint
  - build
  - test27
  - test

# -- stages

check27:
  stage: check27
  image: python:2.7.13
  variables:
    PIP_CACHE_DIR: pip-cache
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - pip install flake8 flake8-docstrings -c constraints.txt
    - make clean
  script:
    - make check
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

check:
  stage: check
  image: python:3.5.4
  variables:
    PIP_CACHE_DIR: pip-cache
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - pip install flake8 flake8-docstrings -c constraints.txt
    - make clean
  script:
    - make check
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

lint27:
  stage: lint27
  image: python:2.7.13
  variables:
    PIP_CACHE_DIR: pip-cache
  before_script:
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
    - ENV=development make setup
    - ENV=test make setup
  script:
    - make lint
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

lint:
  stage: lint
  image: python:3.5.4
  variables:
    PIP_CACHE_DIR: pip-cache
  before_script:
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
    - ENV=development make setup
    - ENV=test make setup
  script:
    - make lint
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

build:
  stage: build
  image: node:8.9.0
  variables:
    NODE_ENV: production
  before_script:
    - node --version
    - npm --version
    - npm install --global gulp-cli
    - npm install --ignore-scripts
  script:
    - make build
  cache:
    untracked: true
    paths:
      - node_modules
  artifacts:
    untracked: true
    paths:
      - static
  except:
    - tags

test27:
  stage: test27
  image: python:3.5.4
  variables:
    PIP_CACHE_DIR: pip-cache
    ENV: test
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - ENV=test make setup
  script:
    #- make coverage
    - make test
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

test:
  stage: test
  image: python:3.5.4
  variables:
    PIP_CACHE_DIR: pip-cache
    ENV: test
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - ENV=test make setup
  script:
    - make coverage
  cache:
    untracked: true
    paths:
      - pip-cache
  artifacts:
    untracked: true
    paths:
      - .coverage
  except:
    - tags
