# https;//docs.gitlab.com/ce/ci/yaml/
stages:
  - check27
  - check
  - lint27
  - lint
  - build

variables:
  PIP_CACHE_DIR: pip-cache

cache:
  untracked: true
  paths:
    - pip-cache
    - node_modules

# -- stages

check27:
  stage: check27
  image: python:2.7.13
  before_script:
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
    - pip install flake8 flake8-docstrings -c constraints.txt
    - make clean
  script:
    - make check
  except:
    - tags

check:
  stage: check
  image: python:3.5.4
  before_script:
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
    - pip install flake8 flake8-docstrings -c constraints.txt
    - make clean
  script:
    - make check
  except:
    - tags

lint27:
  stage: lint27
  image: python:2.7.13
  before_script:
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
    - ENV=development make setup
    - ENV=test make setup
  script:
    - make lint
  except:
    - tags

lint:
  stage: lint
  image: python:3.5.4
  before_script:
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
    - ENV=development make setup
    - ENV=test make setup
  script:
    - make lint
  except:
    - tags

build:
  stage: build
  image: node:7.10.1
  variables:
    NODE_ENV: production
  before_script:
    - node --version
    - npm --version
    - npm install --global gulp-cli
    - npm install --ignore-scripts
  script:
    - make build
  artifacts:
    untracked: true
    paths:
      - static
  except:
    - tags
